### ISSUE TITLE
效果差于https://github.com/jhfmat/ISP-pipeline-hdrplus 

### ISSUE THREAD

**Issue by jhfmat** [cruxopen/openISP#14]
https://github.com/jhfmat/ISP-pipeline-hdrplus

**Comment by cruxopen** [comment]
I don't think they should be comparable. Yours aims to run on Win/Linux/Android etc. Mine is designed as a simple demo to illustrate how ISP pipeline works and how to design the ISP pipeline in HW, which considers a lot of other factors, rather than algorithms itself. Again, my ISP pipeline was designed several years ago and this repo was not maintained for a long time. The repo was for the fresh who willing to this area. If for comercial purpose, I am happy to license some **fascinating** stuffs.
Also ISP pipeline is designed for HW processor that handles a various of situations in video instead of some static images. To be honest, I didn't look into your design. From your results, it looks good. Some samples seems captured at Intellif ? I guess your ISP design focused on survillance camera and low-light or HDR is a sellpoint for the product, but I am hundred precent sure that the hardwarization is not easy at least not as good as your demo. 
Anyway it is glad to see a number of people devote to this area.
